### ISSUE TITLE
Debian 9 纯净系统安装官网warp客户端报错

### ISSUE THREAD

**Issue by zhucaidan** [P3TERX/warp.sh#1]
第一次报错是“N: Is the package apt-transport-https installed?”通过apt-get install -y apt-transport-https解决

然后尝试第二次安装，报错为：
“Errors were encountered while processing:
 cloudflare-warp
E: Sub-process /usr/bin/dpkg returned an error code (1)
[ERROR] warp-svc failure to run!
-- No entries --”

**Comment by P3TERX** [comment]
感谢反馈，后续会加入对`apt-transport-https`的安装。我之前测试 Debian 9 直接安装很顺利，你这个系统应该是太纯净了。

第二次安装关键问题应该在于：
```
E: Sub-process /usr/bin/dpkg returned an error code (1)
```
解决方法可以参考[这篇文章](https://www.cnblogs.com/bymo/p/9046586.html)。

如果还是实在安装不了建议重装系统或者换 Debian 10。

**Comment by zhucaidan** [comment]
好的，我去切换Debian 10试一下；另外还有个问题想请教下，

就是当vps使用wireguard开启warp后，假如使用的是vless+nginx反代协议连接vps的话是可以让出口是warp的IP

但是如果vps服务端是SS或者SSR，MTP代理这种协议的代理连接的话，出口IP检测均为vps的原始IP

不知道这是为何？按道理应该是wgcf的网卡接管全部出站流量不是吗？（用本机curl检测是warp的IP）

**Comment by P3TERX** [comment]
不知道你是用的什么方法检测的，如果检测的网站用了 CF CDN 就会显示原始 IP 。
