### ISSUE TITLE
Rate limit exceeded

### ISSUE THREAD

**Issue by sgalcheung** [P3TERX/warp.sh#100]
curl ipinfo.io 
{   "status": 429,   "error": {     "title": "Rate limit exceeded",     "message": "You've hit the daily limit for the unauthenticated API.  Create an API access token by signing up to get 50k req/month."   }

sometime is response ok, and org is Cloudflare, Inc.

**Comment by P3TERX** [comment]
WARP 是很多人共用一个出口 IP ，同一 IP 用 ipinfo.io 查询的人很多就会提示限制。

**Comment by sgalcheung** [comment]
那为啥还是访问不到 Chat GPT ，New Bing

**Comment by sgalcheung** [comment]
我后面发现win可以，mac和iPhone不行
这是因为bing.com没有走代理，实际上warp已经不是成功啦，调整 GFW 规则即可
