### ISSUE TITLE
如何让通过SOCKS5-WARP代理时直接走ipv6

### ISSUE THREAD

**Issue by 738NGX** [P3TERX/warp.sh#103]
我在设置sock5代理规则时只让chatgpt走了warp，但是socks默认走的两个ipv4地址也被openai ban了，但是如果用Windows客户端他走的ipv6是可以上的。不过他客户端用的时候我电脑会有些软件的功能受影响（比如远程串流），所以有没有办法让在VPS上的socks5也走ipv6？

**Comment by toyo2333** [comment]
同问：我的问题在这里：

我说说的情况：

我是双栈机器，原本vps就可以访问ChatGTP，浏览器打开 https://chat.openai.com/cdn-cgi/trace 里可以看到IP使用了VPS自己的IPv6地址。

我的目的也很简单就是：再套一层warp（用Warp-cli set-mode proxy的socks代理模式，只想用这个模式）， 最终让浏览器以warp的IPv6访问ChatGTP。

配置下来后：

1，在VPS上用curl https://chat.openai.com/cdn-cgi/trace --proxy socks5://127.0.0.1:40000 确认VPS默认优先使用了warp的IPv6访问了chatgpt，没问题

2，但我电脑用浏览器访问，但是却显示用了Warp的IPv4地址（还是通过上面的地址查看）。

我想了下，我浏览器应该没问题，因为原本就可以IPv6访问，VPS也没问题，因为上述命令行也是通过代理转发，所以也不是代理模式的问题。那就只能是Xray的问题了？实在搞不懂哪里出了问题，我的配置是这样的，改动的很少：

路由规则如下，增加了分流路由：

```
   {
        "type": "field",
        "outboundTag": "warp",
        "domain": [
			"openai.com",
			"ai.com",
			"chat.openai.com.cdn.cloudflare.net",
			"openaiapi-site.azureedge.net",
			"ip.sb"
        ]
      },
```
出站代理和网上的教程一样设置转发到socks协议的40000端口，发现只能走warp的IPv4后，我试了下面两种指定"UseIPv6"的设置都不行，无效！！

设置1：增加"streamSettings"，在底层sockopt设置策略

   ```
 {
      "tag": "warp",
      "protocol": "socks",
      "streamSettings": {
	  "sockopt": {"domainStrategy": "UseIPv6"}
	  },
      "settings": {
        "servers": [
          {
            "address": "127.0.0.1",
            "port": 40000
          }
        ]
      }
    },
```

设置2：直接在settings里增加策略


```
	{
      "tag": "warp",
      "protocol": "socks",
      "settings": {
	   "domainStrategy": "UseIPv6"
        "servers": [
          {
            "address": "127.0.0.1",
            "port": 40000
          }
        ]
      }
    },
```
无论怎么改都不行，恳请 分析下哪里有问题，该如何实现我的需求（在用proxy模式的前提下）？

**Comment by toyo2333** [comment]
> 我在设置sock5代理规则时只让chatgpt走了warp，但是socks默认走的两个ipv4地址也被openai ban了，但是如果用Windows客户端他走的ipv6是可以上的。不过他客户端用的时候我电脑会有些软件的功能受影响（比如远程串流），所以有没有办法让在VPS上的socks5也走ipv6？

我和你遇到的应该同样的问题和需求，看我上面的内容

**Comment by 738NGX** [comment]
> > 我在设置sock5代理规则时只让chatgpt走了warp，但是socks默认走的两个ipv4地址也被openai ban了，但是如果用Windows客户端他走的ipv6是可以上的。不过他客户端用的时候我电脑会有些软件的功能受影响（比如远程串流），所以有没有办法让在VPS上的socks5也走ipv6？
> 
> 我和你遇到的应该同样的问题和需求，看我上面的内容

我还要离谱一点，我VPS里面也一样是IPV4

**Comment by toyo2333** [comment]
> > > 我在设置sock5代理规则时只让chatgpt走了warp，但是socks默认走的两个ipv4地址也被openai ban了，但是如果用Windows客户端他走的ipv6是可以上的。不过他客户端用的时候我电脑会有些软件的功能受影响（比如远程串流），所以有没有办法让在VPS上的socks5也走ipv6？
> > 
> > 
> > 我和你遇到的应该同样的问题和需求，看我上面的内容
> 
> 我还要离谱一点，我VPS里面也一样是IPV4

可能只能用wgcf这个第三方客户端了。

**Comment by toyo2333** [comment]
> > > 我在设置sock5代理规则时只让chatgpt走了warp，但是socks默认走的两个ipv4地址也被openai ban了，但是如果用Windows客户端他走的ipv6是可以上的。不过他客户端用的时候我电脑会有些软件的功能受影响（比如远程串流），所以有没有办法让在VPS上的socks5也走ipv6？
> > 
> > 
> > 我和你遇到的应该同样的问题和需求，看我上面的内容
> 
> 我还要离谱一点，我VPS里面也一样是IPV4

经过我研究，已经搞定。不能用proxy模式，建议用这位作者的脚本搞定
1，运行它的脚本，先卸载warp-cli客户端 
2，然后选里面6，自动安装并配置IPv6这个选项。

做这个测试看看接管是否成功：
`curl -6 ip.p3terx.com`

如果成功了，那就可以了。


3，如果有问题，就强制做一下域名转发处理，比如xray的配置里增加一个outbound
```
{
      "tag": "IP6_out",
      "protocol": "freedom",
      "settings": {
        "domainStrategy": "UseIPv6"
      }
    },
```
再增加一个路由规则，把chatgpt流量转到这个outbund就可以了。


我这里openai默认走v6的，所以我不需要步骤3，步骤2配置完成后，就好了。

**Comment by 738NGX** [comment]
> > > > 我在设置sock5代理规则时只让chatgpt走了warp，但是socks默认走的两个ipv4地址也被openai ban了，但是如果用Windows客户端他走的ipv6是可以上的。不过他客户端用的时候我电脑会有些软件的功能受影响（比如远程串流），所以有没有办法让在VPS上的socks5也走ipv6？
> > > 
> > > 
> > > 我和你遇到的应该同样的问题和需求，看我上面的内容
> > 
> > 
> > 我还要离谱一点，我VPS里面也一样是IPV4
> 
> 经过我研究，已经搞定。不能用proxy模式，建议用这位作者的脚本搞定 1，运行它的脚本，先卸载warp-cli客户端 2，然后选里面6，自动安装并配置IPv6这个选项。
> 
> 做这个测试看看接管是否成功： `curl -6 ip.p3terx.com`
> 
> 如果成功了，那就可以了。
> 
> 3，如果有问题，就强制做一下域名转发处理，比如xray的配置里增加一个outbound
> 
> ```
> {
>       "tag": "IP6_out",
>       "protocol": "freedom",
>       "settings": {
>         "domainStrategy": "UseIPv6"
>       }
>     },
> ```
> 
> 再增加一个路由规则，把chatgpt流量转到这个outbund就可以了。
> 
> 我这里openai默认走v6的，所以我不需要步骤3，步骤2配置完成后，就好了。

所以说。。。是哪个脚本？

**Comment by toyo2333** [comment]
> > > > > 我在设置sock5代理规则时只让chatgpt走了warp，但是socks默认走的两个ipv4地址也被openai ban了，但是如果用Windows客户端他走的ipv6是可以上的。不过他客户端用的时候我电脑会有些软件的功能受影响（比如远程串流），所以有没有办法让在VPS上的socks5也走ipv6？
> > > > 
> > > > 
> > > > 我和你遇到的应该同样的问题和需求，看我上面的内容
> > > 
> > > 
> > > 我还要离谱一点，我VPS里面也一样是IPV4
> > 
> > 
> > 经过我研究，已经搞定。不能用proxy模式，建议用这位作者的脚本搞定 1，运行它的脚本，先卸载warp-cli客户端 2，然后选里面6，自动安装并配置IPv6这个选项。
> > 做这个测试看看接管是否成功： `curl -6 ip.p3terx.com`
> > 如果成功了，那就可以了。
> > 3，如果有问题，就强制做一下域名转发处理，比如xray的配置里增加一个outbound
> > ```
> > {
> >       "tag": "IP6_out",
> >       "protocol": "freedom",
> >       "settings": {
> >         "domainStrategy": "UseIPv6"
> >       }
> >     },
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 再增加一个路由规则，把chatgpt流量转到这个outbund就可以了。
> > 我这里openai默认走v6的，所以我不需要步骤3，步骤2配置完成后，就好了。
> 
> 所以说。。。是哪个脚本？

https://github.com/P3TERX/warp.sh

**Comment by 738NGX** [comment]
> > > > > > 我在设置sock5代理规则时只让chatgpt走了warp，但是socks默认走的两个ipv4地址也被openai ban了，但是如果用Windows客户端他走的ipv6是可以上的。不过他客户端用的时候我电脑会有些软件的功能受影响（比如远程串流），所以有没有办法让在VPS上的socks5也走ipv6？
> > > > > 
> > > > > 
> > > > > 我和你遇到的应该同样的问题和需求，看我上面的内容
> > > > 
> > > > 
> > > > 我还要离谱一点，我VPS里面也一样是IPV4
> > > 
> > > 
> > > 经过我研究，已经搞定。不能用proxy模式，建议用这位作者的脚本搞定 1，运行它的脚本，先卸载warp-cli客户端 2，然后选里面6，自动安装并配置IPv6这个选项。
> > > 做这个测试看看接管是否成功： `curl -6 ip.p3terx.com`
> > > 如果成功了，那就可以了。
> > > 3，如果有问题，就强制做一下域名转发处理，比如xray的配置里增加一个outbound
> > > ```
> > > {
> > >       "tag": "IP6_out",
> > >       "protocol": "freedom",
> > >       "settings": {
> > >         "domainStrategy": "UseIPv6"
> > >       }
> > >     },
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 再增加一个路由规则，把chatgpt流量转到这个outbund就可以了。
> > > 我这里openai默认走v6的，所以我不需要步骤3，步骤2配置完成后，就好了。
> > 
> > 
> > 所以说。。。是哪个脚本？
> 
> https://github.com/P3TERX/warp.sh

我用的就是这个脚本，现在的情况是VPS已经可以用ipv6访问到chatgpt了，但是用PC浏览器依然还是ipv4

**Comment by 738NGX** [comment]
> > > > > > 我在设置sock5代理规则时只让chatgpt走了warp，但是socks默认走的两个ipv4地址也被openai ban了，但是如果用Windows客户端他走的ipv6是可以上的。不过他客户端用的时候我电脑会有些软件的功能受影响（比如远程串流），所以有没有办法让在VPS上的socks5也走ipv6？
> > > > > 
> > > > > 
> > > > > 我和你遇到的应该同样的问题和需求，看我上面的内容
> > > > 
> > > > 
> > > > 我还要离谱一点，我VPS里面也一样是IPV4
> > > 
> > > 
> > > 经过我研究，已经搞定。不能用proxy模式，建议用这位作者的脚本搞定 1，运行它的脚本，先卸载warp-cli客户端 2，然后选里面6，自动安装并配置IPv6这个选项。
> > > 做这个测试看看接管是否成功： `curl -6 ip.p3terx.com`
> > > 如果成功了，那就可以了。
> > > 3，如果有问题，就强制做一下域名转发处理，比如xray的配置里增加一个outbound
> > > ```
> > > {
> > >       "tag": "IP6_out",
> > >       "protocol": "freedom",
> > >       "settings": {
> > >         "domainStrategy": "UseIPv6"
> > >       }
> > >     },
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 再增加一个路由规则，把chatgpt流量转到这个outbund就可以了。
> > > 我这里openai默认走v6的，所以我不需要步骤3，步骤2配置完成后，就好了。
> > 
> > 
> > 所以说。。。是哪个脚本？
> 
> https://github.com/P3TERX/warp.sh

啊我又弄了一下现在上确实能上gpt了，不过现在似乎是所有流量都走了warp？实际上我需要走的好像也就gpt

**Comment by 738NGX** [comment]
> > > > > > 我在设置sock5代理规则时只让chatgpt走了warp，但是socks默认走的两个ipv4地址也被openai ban了，但是如果用Windows客户端他走的ipv6是可以上的。不过他客户端用的时候我电脑会有些软件的功能受影响（比如远程串流），所以有没有办法让在VPS上的socks5也走ipv6？
> > > > > 
> > > > > 
> > > > > 我和你遇到的应该同样的问题和需求，看我上面的内容
> > > > 
> > > > 
> > > > 我还要离谱一点，我VPS里面也一样是IPV4
> > > 
> > > 
> > > 经过我研究，已经搞定。不能用proxy模式，建议用这位作者的脚本搞定 1，运行它的脚本，先卸载warp-cli客户端 2，然后选里面6，自动安装并配置IPv6这个选项。
> > > 做这个测试看看接管是否成功： `curl -6 ip.p3terx.com`
> > > 如果成功了，那就可以了。
> > > 3，如果有问题，就强制做一下域名转发处理，比如xray的配置里增加一个outbound
> > > ```
> > > {
> > >       "tag": "IP6_out",
> > >       "protocol": "freedom",
> > >       "settings": {
> > >         "domainStrategy": "UseIPv6"
> > >       }
> > >     },
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 再增加一个路由规则，把chatgpt流量转到这个outbund就可以了。
> > > 我这里openai默认走v6的，所以我不需要步骤3，步骤2配置完成后，就好了。
> > 
> > 
> > 所以说。。。是哪个脚本？
> 
> https://github.com/P3TERX/warp.sh

而且这个连上之后不久又断掉了，还要手动重启。。

**Comment by 738NGX** [comment]
现在找到了一种似乎稳定的解决方法,通过路由标记的方式来分流,先运行这个脚本:
```
bash <(curl -fsSL git.io/warp.sh) x
```
然后在/etc/v2ray/config.json里设置出站规则:
```
"outbounds": [
        ......
        {
            "tag": "WARP_out",
            "protocol": "freedom",
            "streamSettings": {
                "sockopt": {
                    "mark": 51888
                }
            },
            "settings": {
                "domainStrategy": "UseIPv6"
            }
        },
        ......
],
"routing": {
        ......
        "rules": [
           ......
            {
                "domain": [
                    "domain:openai.com",
                    "domain:bing.com",
                ],
                "outboundTag": "WARP_out",
                "type": "field"
            },
      ......
     ]
},
```
到现在未知还在稳定运行,如果明天早上他还活着我就关issue了)

**Comment by toyo2333** [comment]
> PC浏览器依然还是i

> 现在找到了一种似乎稳定的解决方法,通过路由标记的方式来分流,先运行这个脚本:
> 
> ```
> bash <(curl -fsSL git.io/warp.sh) x
> ```
> 
> 然后在/etc/v2ray/config.json里设置出站规则:
> 
> ```
> "outbounds": [
>         ......
>         {
>             "tag": "WARP_out",
>             "protocol": "freedom",
>             "streamSettings": {
>                 "sockopt": {
>                     "mark": 51888
>                 }
>             },
>             "settings": {
>                 "domainStrategy": "UseIPv6"
>             }
>         },
>         ......
> ],
> "routing": {
>         ......
>         "rules": [
>            ......
>             {
>                 "domain": [
>                     "domain:openai.com",
>                     "domain:bing.com",
>                 ],
>                 "outboundTag": "WARP_out",
>                 "type": "field"
>             },
>       ......
>      ]
> },
> ```
> 
> 到现在为止还在稳定运行,如果明天早上他还活着我就关issue了)

好方法~我是只接管了全局V6，加上GPT的方法本身也是走V6，所以不用去单独设置域名策略了。

能解决就好。
