### ISSUE TITLE
在Debian11上proxy模式状态总是没启用

### ISSUE THREAD

**Issue by toyo2333** [P3TERX/warp.sh#108]
中文菜单里，选1 安装客户端
2，配置proxy

结果就是，状态始终是未连接。

**Comment by toyo2333** [comment]
找到原因了，linux的内核太旧了，5.10.0-14-cloud-amd64，我更新内核到5.10.0-22-cloud-amd64就接解决了。

另外一台机器上5.10.0-17-cloud-amd64也没问题。

**Comment by bigtree945** [comment]
LXC 可以升级 Linux 的内核吗

**Comment by bigtree945** [comment]
好的，感谢
