### ISSUE TITLE
wgcf installation failed

### ISSUE THREAD

**Issue by Andy-Chuck** [P3TERX/warp.sh#11]
CentOS 8
使用一键脚本安装时提示wgcf installation failed，此后一直循环这条信息。
Azure 的鸡子。
![pic](https://user-images.githubusercontent.com/54295429/126175523-7e6defe5-8d67-4ea8-bc0c-35b064a580c9.png)

**Comment by P3TERX** [comment]
感谢反馈。
问题出在系统 PATH 中没有`/usr/local/bin`，部分 IDC 提供的 CentOS 镜像会有这个问题。我用的测试环境没遇到，所以脚本没对此进行特别处理。
刚刚对脚本进行了改进，理论上应该没问题了。

**Comment by Andy-Chuck** [comment]
已可以安装。
深夜起来改代码，辛苦你了。
