### ISSUE TITLE
Need update script to work with Debian 12 "bookworm" release

### ISSUE THREAD

**Issue by Rennats** [P3TERX/warp.sh#117]
Now:
    elif [[ ${SysInfo_OS_Name_lowercase} = debian ]]; then
        case ${SysInfo_OS_CodeName} in
        buster | bullseye) ;;

Need:
    elif [[ ${SysInfo_OS_Name_lowercase} = debian ]]; then
        case ${SysInfo_OS_CodeName} in
        buster | bullseye | bookworm) ;;

**Comment by useribs** [comment]
I second that, author should merge #112
