### ISSUE TITLE
warp 客户端 socks5 代理开启不了

### ISSUE THREAD

**Issue by BaileyZyp** [P3TERX/warp.sh#12]
![image](https://user-images.githubusercontent.com/16634459/126623252-1b1f56bf-342e-41a8-8ec5-6053c383d09d.png)
![image](https://user-images.githubusercontent.com/16634459/126623286-c10794fa-8783-4ffa-962b-a6b77f487d3f.png)

系统是 Ubuntu 20.04.1

**Comment by BaileyZyp** [comment]
机器是 AWS JP

**Comment by sparrowjack** [comment]
+1

**Comment by BaileyZyp** [comment]
@sparrowjack 手动运行一次warp注册命令就可以了，我前两天本来想手动部署一下 发现运行注册命令就能启动了

**Comment by P3TERX** [comment]
WARP 客户端最近更新了一波，有些改动。刚刚修复了。

**Comment by liuyoujiu** [comment]
> WARP 客户端最近更新了一波，有些改动。刚刚修复了。
WARP又更新了，同意之后，还需要再手动注册才可以运行🤣
![image](https://user-images.githubusercontent.com/92580531/139571967-57dbca2a-269e-48fe-8617-e4a92b62b70f.png)
