### ISSUE TITLE
切换用户时提示 unable to resolve host

### ISSUE THREAD

**Issue by Andy-Chuck** [P3TERX/warp.sh#14]
只是一点小问题，不知道是哪里出错了，也不太清楚是否对其他地方有影响。

使用脚本安装、开启Warp后，每次切换用户（sudo su root）时会提示
sudo: unable to resolve host ***: Name or service not known.

![PIC](https://user-images.githubusercontent.com/54295429/127735790-864aeaf8-4817-4805-8db9-ee07cf82c33c.png)

环境信息：
Ubuntu 20.02, amd64, kvm

**Comment by P3TERX** [comment]
与这个脚本无关，请善用搜索。
