### ISSUE TITLE
debian 9 VERSION_CODENAME 值为空

### ISSUE THREAD

**Issue by github125132** [P3TERX/warp.sh#18]
自己在 debian 9 上使用脚本

报错
```
deb http://pkg.cloudflareclient.com/  main
E: Malformed entry 1 in list file /etc/apt/sources.list.d/cloudflare-client.list (Component)
E: The list of sources could not be read.
```
简单看了下脚本，是不是因为 VERSION_CODENAME 没有赋值导致值为空啊？

**Comment by P3TERX** [comment]
看这日志应该是没赋值，可能 Debian 9 的`os-release`文件中没有 `VERSION_CODENAME`字段。
刚刚改进了下脚本，理论上没问题了，我暂时没 Debian 9 的环境，你可以试一下。

**Comment by github125132** [comment]
首先感谢作者更新

现在 Debian 9 上，安装顺利，启动报错
运行命令
`bash <(curl -fsSL git.io/warp.sh) d`
最后报错
```
systemd[1]: wg-quick@wgcf.service: Main process exited, code=exited, status=1/FAILURE
systemd[1]: Failed to start WireGuard via wg-quick(8) for wgcf.
systemd[1]: wg-quick@wgcf.service: Unit entered failed state.
systemd[1]: wg-quick@wgcf.service: Failed with result 'exit-code'.
```
根据别的 Issue 进行卸载、重启 vps 、重新安装，错误依旧。

**Comment by P3TERX** [comment]
> 首先感谢作者更新
> 
> 现在 Debian 9 上，安装顺利，启动报错
> 运行命令
> `bash <(curl -fsSL git.io/warp.sh) d`
> 最后报错
> 
> ```
> systemd[1]: wg-quick@wgcf.service: Main process exited, code=exited, status=1/FAILURE
> systemd[1]: Failed to start WireGuard via wg-quick(8) for wgcf.
> systemd[1]: wg-quick@wgcf.service: Unit entered failed state.
> systemd[1]: wg-quick@wgcf.service: Failed with result 'exit-code'.
> ```
> 
> 根据别的 Issue 进行卸载、重启 vps 、重新安装，错误依旧。

把日志截全。这日志只能看出错误退出了，没有原因。

**Comment by P3TERX** [comment]
整了个 Debian 9 环境测。实测 WARP 官方客户端无法正常在 Debian 9 上运行，而且安装它会附带安装 nftables ，这又会导致 WireGuard 无法正常启动。

执行`apt autoremove -y --purge nftables`可解，不要再装 WARP 官方客户端了。

另外建议用 Debian 10+。后续更新我可能会禁止 Debian 9 使用这个脚本，系统太老官方都没有在维护了，乱七八糟的问题太多了，已经不值得做适配了。
