### ISSUE TITLE
WARP客户端状态，未运行。

### ISSUE THREAD

**Issue by XavierLee-0** [P3TERX/warp.sh#19]
```
System Information
 Operating System: Debian GNU/Linux 10 (buster)
     Linux Kernel: 5.4.123-1.el7.elrepo.x86_64
     Architecture: x86_64
     Virtualization: lxc
```

脚本执行完毕后，用ping命令分别ping了谷歌和百度，发现谷歌返回的是ipv6的地址，百度返回的是ipv4的地址。
![image](https://user-images.githubusercontent.com/63280021/131212158-2e678a82-38fe-4dfb-bf4c-2806c7e3c890.png)

查看菜单看到WARP客户端处于未运行状态，请问有影响吗？
![image](https://user-images.githubusercontent.com/63280021/131212149-d6f042bf-798f-413c-8425-86305d076b65.png)

**Comment by XavierLee-0** [comment]
执行的是`bash <(curl -fsSL git.io/warp.sh) 4`命令

**Comment by P3TERX** [comment]
1. 如果网站有 IPv6 地址，那么 ping 默认 IPv6 优先。百度应该是没有 IPv6 的。
2. 一个是 WARP 官方客户端，一个是 WireGuard ，是两种不同的 WARP 网络使用方式。你用的是 WireGuard 去接管 IPv4 网络，这个没问题。
