### ISSUE TITLE
有什么办法可以更新wgcf

### ISSUE THREAD

**Issue by Potterli20** [P3TERX/warp.sh#21]
有什么办法可以更新wgcf，在原有的配置文件上只更新wgcf程序

**Comment by Potterli20** [comment]
curl -fsSL git.io/wgcf.sh | sudo bash
每次用这个脚本我都很怕

**Comment by P3TERX** [comment]
wgcf 的作用生成 WARP 的通用 WireGuard 配置文件，只是在生成配置文件的时候用得到一次，然后就没有其它作用了，不需要你自己再去安装或者更新。

如果你是想自己用 wgcf 搞其它骚操作，安装和更新可以用 wgcf.sh 这个脚本。

**Comment by Potterli20** [comment]
> wgcf 的作用是生成 WARP 的通用 WireGuard 配置文件，只是在生成配置文件的时候用得到一次，然后就没有其它作用了，不需要你自己再去安装或者更新。
> 
> 如果你是想自己用 wgcf 搞其它骚操作，安装和更新可以用 wgcf.sh 这个脚本。

其实我更想要的程序更新😂，如果你能写进去检测程序版本更新就好😂
