### ISSUE TITLE
本来成功了，后来想启动个ipv4。就报错了。请帮忙看下。

### ISSUE THREAD

**Issue by asdfvv** [P3TERX/warp.sh#22]
Sep 02 17:39:53 debian wg-quick[15407]: [#] resolvconf -d wgcf -f
Sep 02 17:39:53 debian wg-quick[15407]: Too few arguments.
Sep 02 17:39:53 debian wg-quick[15407]: Too few arguments.
Sep 02 17:39:53 debian wg-quick[15407]: [#] ip -6 rule delete table 51820
Sep 02 17:39:53 debian wg-quick[15407]: [#] ip -6 rule delete table main suppress_prefixlength 0
Sep 02 17:39:53 debian wg-quick[15407]: [#] ip link delete dev wgcf
Sep 02 17:39:53 debian systemd[1]: wg-quick@wgcf.service: Main process exited, code=exited, status=1/FAILURE
Sep 02 17:39:53 debian systemd[1]: Failed to start WireGuard via wg-quick(8) for wgcf.
Sep 02 17:39:53 debian systemd[1]: wg-quick@wgcf.service: Unit entered failed state.
Sep 02 17:39:53 debian systemd[1]: wg-quick@wgcf.service: Failed with result 'exit-code'.
Sep 02 17:42:40 debian systemd[1]: Starting WireGuard via wg-quick(8) for wgcf...
Sep 02 17:42:40 debian wg-quick[16248]: [#] ip link add wgcf type wireguard
Sep 02 17:42:40 debian wg-quick[16248]: RTNETLINK answers: Operation not supported
Sep 02 17:42:40 debian wg-quick[16248]: [!] Missing WireGuard kernel module. Falling back to slow userspace implementation.
Sep 02 17:42:40 debian wg-quick[16248]: [#] wireguard-go wgcf
Sep 02 17:42:40 debian wg-quick[16248]: ┌──────────────────────────────────────────────────────┐
Sep 02 17:42:40 debian wg-quick[16248]: │                                                      │
Sep 02 17:42:40 debian wg-quick[16248]: │   Running wireguard-go is not required because this  │
Sep 02 17:42:40 debian wg-quick[16248]: │   kernel has first class support for WireGuard. For  │
Sep 02 17:42:40 debian wg-quick[16248]: │   information on installing the kernel module,       │
Sep 02 17:42:40 debian wg-quick[16248]: │   please visit:                                      │
Sep 02 17:42:40 debian wg-quick[16248]: │         https://www.wireguard.com/install/           │
Sep 02 17:42:40 debian wg-quick[16248]: │                                                      │
Sep 02 17:42:40 debian wg-quick[16248]: └──────────────────────────────────────────────────────┘
Sep 02 17:42:40 debian wg-quick[16248]: [#] wg setconf wgcf /dev/fd/63
Sep 02 17:42:40 debian wg-quick[16248]: [#] ip -4 address add 172.16.0.2/32 dev wgcf
Sep 02 17:42:40 debian wg-quick[16248]: [#] ip -6 address add fd01:5ca1:ab1e:80bb:ab9e:5353:d837:2a8d/128 dev wgcf
Sep 02 17:42:40 debian wg-quick[16248]: [#] ip link set mtu 1280 up dev wgcf
Sep 02 17:42:40 debian wg-quick[16248]: [#] resolvconf -a wgcf -m 0 -x
Sep 02 17:42:40 debian wg-quick[16248]: Too few arguments.
Sep 02 17:42:40 debian wg-quick[16248]: Too few arguments.
Sep 02 17:42:40 debian wg-quick[16248]: [#] wg set wgcf fwmark 51820
Sep 02 17:42:40 debian wg-quick[16248]: [#] ip -6 route add ::/0 dev wgcf table 51820
Sep 02 17:42:40 debian wg-quick[16248]: [#] ip -6 rule add not fwmark 51820 table 51820
Sep 02 17:42:40 debian wg-quick[16248]: [#] ip -6 rule add table main suppress_prefixlength 0
Sep 02 17:42:40 debian wg-quick[16248]: [#] nft -f /dev/fd/63
Sep 02 17:42:40 debian wg-quick[16248]: /dev/fd/63:5:1-131: Error: Could not process rule: No such file or directory
Sep 02 17:42:40 debian wg-quick[16248]: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Sep 02 17:42:40 debian wg-quick[16248]: /dev/fd/63:6:1-117: Error: Could not process rule: No such file or directory
Sep 02 17:42:40 debian wg-quick[16248]: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Sep 02 17:42:40 debian wg-quick[16248]: [#] resolvconf -d wgcf -f
Sep 02 17:42:40 debian wg-quick[16248]: Too few arguments.
Sep 02 17:42:40 debian wg-quick[16248]: Too few arguments.
Sep 02 17:42:40 debian wg-quick[16248]: [#] ip -6 rule delete table 51820
Sep 02 17:42:40 debian wg-quick[16248]: [#] ip -6 rule delete table main suppress_prefixlength 0
Sep 02 17:42:40 debian wg-quick[16248]: [#] ip link delete dev wgcf
Sep 02 17:42:40 debian systemd[1]: wg-quick@wgcf.service: Main process exited, code=exited, status=1/FAILURE
Sep 02 17:42:40 debian systemd[1]: Failed to start WireGuard via wg-quick(8) for wgcf.
Sep 02 17:42:40 debian systemd[1]: wg-quick@wgcf.service: Unit entered failed state.
Sep 02 17:42:40 debian systemd[1]: wg-quick@wgcf.service: Failed with result 'exit-code'.
root@debian:~# curl: (23) Failed writing body (496 != 1371)

**Comment by P3TERX** [comment]
偶发性 bug ，重启、重装

**Comment by 1-1-2** [comment]
在VPS上测试warp.sh的时候遇到了同样的问题。做过的操作依次为：

1. 自动配置 WARP WireGuard 双栈全局网络
2. 关闭 WARP WireGuard 网络
3. 置换 IPv6 为 WARP 网络
4. 自动配置 WARP 官方客户端 SOCKS5 代理
5. 自动配置 WARP WireGuard 双栈全局网络

然后就开始失败报错了，随后尝试进行过：

1. 卸载 WARP 官方客户端
2. 自动配置 WARP WireGuard 双栈全局网络
3. 置换 IPv4/IPv6 为 WARP 网络 (IPv4 节点)
4. 添加 WARP IPv4 网络，置换 IPv6 为 WARP 网络

依旧出现相同的报错信息

```
Oct 07 22:25:45 O4VM systemd[1]: Starting WireGuard via wg-quick(8) for wgcf...
Oct 07 22:25:45 O4VM wg-quick[1214]: [#] ip link add wgcf type wireguard
Oct 07 22:25:45 O4VM wg-quick[1214]: RTNETLINK answers: Operation not supported
Oct 07 22:25:45 O4VM wg-quick[1214]: [!] Missing WireGuard kernel module. Falling back to slow userspace implementation.
Oct 07 22:25:45 O4VM wg-quick[1214]: [#] wireguard-go wgcf
Oct 07 22:25:45 O4VM wg-quick[1214]: ┌──────────────────────────────────────────────────────┐
Oct 07 22:25:45 O4VM wg-quick[1214]: │                                                      │
Oct 07 22:25:45 O4VM wg-quick[1214]: │   Running wireguard-go is not required because this  │
Oct 07 22:25:45 O4VM wg-quick[1214]: │   kernel has first class support for WireGuard. For  │
Oct 07 22:25:45 O4VM wg-quick[1214]: │   information on installing the kernel module,       │
Oct 07 22:25:45 O4VM wg-quick[1214]: │   please visit:                                      │
Oct 07 22:25:45 O4VM wg-quick[1214]: │         https://www.wireguard.com/install/           │
Oct 07 22:25:45 O4VM wg-quick[1214]: │                                                      │
Oct 07 22:25:45 O4VM wg-quick[1214]: └──────────────────────────────────────────────────────┘
Oct 07 22:25:45 O4VM wg-quick[1214]: [#] wg setconf wgcf /dev/fd/63
Oct 07 22:25:45 O4VM wg-quick[1214]: [#] ip -4 address add 172.16.0.2/32 dev wgcf
Oct 07 22:25:45 O4VM wg-quick[1214]: [#] ip -6 address add fd01:5ca1:ab1e:83d0:6ab6:9baf:1c9a:e895/128 dev wgcf
Oct 07 22:25:45 O4VM wg-quick[1214]: [#] ip link set mtu 1420 up dev wgcf
Oct 07 22:25:45 O4VM wg-quick[1214]: [#] resolvconf -a wgcf -m 0 -x
Oct 07 22:25:45 O4VM wg-quick[1214]: Too few arguments.
Oct 07 22:25:45 O4VM wg-quick[1214]: Too few arguments.
Oct 07 22:25:45 O4VM wg-quick[1214]: [#] wg set wgcf fwmark 51820
Oct 07 22:25:45 O4VM wg-quick[1214]: [#] ip -6 route add ::/0 dev wgcf table 51820
Oct 07 22:25:45 O4VM wg-quick[1214]: [#] ip -6 rule add not fwmark 51820 table 51820
Oct 07 22:25:45 O4VM wg-quick[1214]: [#] ip -6 rule add table main suppress_prefixlength 0
Oct 07 22:25:45 O4VM wg-quick[1214]: [#] nft -f /dev/fd/63
Oct 07 22:25:45 O4VM wg-quick[1214]: /dev/fd/63:5:1-131: Error: Could not process rule: No such file or directory
Oct 07 22:25:45 O4VM wg-quick[1214]: /dev/fd/63:6:1-116: Error: Could not process rule: No such file or directory
Oct 07 22:25:45 O4VM wg-quick[1214]: [#] resolvconf -d wgcf -f
Oct 07 22:25:45 O4VM wg-quick[1214]: Too few arguments.
Oct 07 22:25:45 O4VM wg-quick[1214]: Too few arguments.
Oct 07 22:25:45 O4VM wg-quick[1214]: [#] ip -6 rule delete table 51820
Oct 07 22:25:45 O4VM wg-quick[1214]: [#] ip -6 rule delete table main suppress_prefixlength 0
Oct 07 22:25:45 O4VM wg-quick[1214]: [#] ip link delete dev wgcf
Oct 07 22:25:45 O4VM systemd[1]: wg-quick@wgcf.service: Main process exited, code=exited, status=1/FAILURE
Oct 07 22:25:45 O4VM systemd[1]: Failed to start WireGuard via wg-quick(8) for wgcf.
Oct 07 22:25:45 O4VM systemd[1]: wg-quick@wgcf.service: Unit entered failed state.
Oct 07 22:25:45 O4VM systemd[1]: wg-quick@wgcf.service: Failed with result 'exit-code'.
```
