### ISSUE TITLE
Failed to start WireGuard via wg-quick(8) for wgcf.

### ISSUE THREAD

**Issue by nashgoo** [P3TERX/warp.sh#27]
EUserv VPS
CentOS 8
安装报错：Failed to start WireGuard via wg-quick(8) for wgcf.
请问一下如何解决呢？

**Comment by nashgoo** [comment]
systemd[1]: wg-quick@wgcf.service: Main process exited, code=exited, status=1/FAILURE
systemd[1]: wg-quick@wgcf.service: Failed with result 'exit-code'.

**Comment by kknd222** [comment]
我也是，ipv4没问题，装ipv6时
WireGuard failure to run!
 nft -f /dev/fd/63
 /dev/fd/63:5:1-131: Error: Could not process rule: No such file or directory
/dev/fd/63:6:1-117: Error: Could not process rule: No such file or directory
resolvconf -d wgcf -f
Too few arguments.
 Too few arguments.
 ip -6 rule delete table 51820
 ip -6 rule delete table main suppress_prefixlength 0
 ip link delete dev wgcf
wg-quick@wgcf.service: Main process exited, code=exited, status=1/FAILURE
Failed to start WireGuard via wg-quick(8) for wgcf.
wg-quick@wgcf.service: Unit entered failed state.
wg-quick@wgcf.service: Failed with result 'exit-code'.

**Comment by P3TERX** [comment]
> EUserv VPS
> CentOS 8
> 安装报错：Failed to start WireGuard via wg-quick(8) for wgcf.
> 请问一下如何解决呢？

EUserv 用 Debian 10 ，它家用的那个 LXC 瘸腿虚拟化用 CentOS 毛病挺多的。
