### ISSUE TITLE
aws 部署了 warp  

### ISSUE THREAD

**Issue by ghost** [P3TERX/warp.sh#3]
aws 部署了 warp   然后 docker 搭建的 应用    ip 就访问不了   请问怎么解决 谢谢

**Comment by P3TERX** [comment]
Docker 应用在 Bridge 网络模式下确实存在这个问题，暂时没有解决方案。你可以使用 Host 网络模式，或者用 nginx 反代。

**Comment by irol765** [comment]
brook中转好像也不行

**Comment by 2ndMessiah** [comment]
> Docker 应用在 Bridge 网络模式下确实存在这个问题，暂时没有解决方案。你可以使用 Host 网络模式，或者用 nginx 反代。

请问大大可以举个nginx反代的例子吗？a和b的反代关系就好 谢谢
