### ISSUE TITLE
甲骨文arm无法安装

### ISSUE THREAD

**Issue by Loukky** [P3TERX/warp.sh#32]
系统是 
Oracle-Linux-7.9-aarch64
提示不支持此系统

**Comment by P3TERX** [comment]
没对 Oracle-Linux 做适配，DD 成其它系统吧，最好是 Debian

**Comment by shanoaice** [comment]
Oracle Linux 其实不需要适配，去掉 firewalld 以后只需要检测到 ARM 就下载 ARM 的 wgcf 可执行即可，还是希望能支持一下的。

**Comment by P3TERX** [comment]
ARM 从一开始就支持了，主要是 Oracle Linux 我不太了解，我之前甲骨文都直接 DD 成 Debian 了，就加了系统限制。现在 Oracle Linux 可以一把梭了。

**Comment by molezz** [comment]
好像用ubuntu也不行， 只能debian？
```
System Information
---------------------------------------------------
  Operating System: Ubuntu 22.04.2 LTS
      Linux Kernel: 5.15.0-1030-oracle
      Architecture: aarch64
    Virtualization: kvm
---------------------------------------------------

[INFO] Installing Cloudflare WARP Client...
[ERROR] This CPU architecture is not supported: aarch64
```

**Comment by wolfdan666** [comment]
> 好像用ubuntu也不行， 只能debian？
> 
> ```
> System Information
> ---------------------------------------------------
>   Operating System: Ubuntu 22.04.2 LTS
>       Linux Kernel: 5.15.0-1030-oracle
>       Architecture: aarch64
>     Virtualization: kvm
> ---------------------------------------------------
> 
> [INFO] Installing Cloudflare WARP Client...
> [ERROR] This CPU architecture is not supported: aarch64
> ```

我的Ubuntu arm服务器也不行

**Comment by davidlauhn** [comment]
> 好像用ubuntu也不行， 只能debian？
> 
> ```
> System Information
> ---------------------------------------------------
>   Operating System: Ubuntu 22.04.2 LTS
>       Linux Kernel: 5.15.0-1030-oracle
>       Architecture: aarch64
>     Virtualization: kvm
> ---------------------------------------------------
> 
> [INFO] Installing Cloudflare WARP Client...
> [ERROR] This CPU architecture is not supported: aarch64
> ```

一样的结果，手动安装就是 Unable to locate package cloudflare-warp，看来只能DD debian了
