### ISSUE TITLE
配置好了但不能用

### ISSUE THREAD

**Issue by StephenAnboer** [P3TERX/warp.sh#33]
![image](https://user-images.githubusercontent.com/23215828/135611273-ff6616d0-ffd1-4f19-a789-0ad21e226c9f.png)
配置好了，wireguard也运行了，但是ipv6还是没有，不知道为什么

 -------------------------
 WireGuard 状态 : 运行中
 IPv4 网络状态  : 未连接
 IPv6 网络状态  : 未连接

**Comment by JialingRichard** [comment]
> ![image](https://user-images.githubusercontent.com/23215828/135611273-ff6616d0-ffd1-4f19-a789-0ad21e226c9f.png) 配置好了，wireguard也运行了，但是ipv6还是没有，不知道为什么
> 
> WireGuard 状态 : 运行中 IPv4 网络状态 : 未连接 IPv6 网络状态 : 未连接

所以是什么原因啊，谢谢。
