### ISSUE TITLE
安装warp前docker pull正常，安装后pull error

### ISSUE THREAD

**Issue by Jakob-Boy** [P3TERX/warp.sh#35]
`root@debian:~# docker pull debian
Using default tag: latest
Error response from daemon: Get "https://registry-1.docker.io/v2/": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)`
`root@debian:~# docker pull debian:9
Error response from daemon: Get "https://registry-1.docker.io/v2/": dial tcp: lookup registry-1.docker.io on 8.8.8.8:53: read udp 172.16.0.2:58997->8.8.8.8:53: i/o timeout`

**Comment by P3TERX** [comment]
DNS 的问题，重启或者换 DNS 可解。
