### ISSUE TITLE
 SOCKS5 代理端口 : 未开启 系统是debian11

### ISSUE THREAD

**Issue by Potterli20** [P3TERX/warp.sh#38]
Cloudflare WARP 一键配置脚本 [beta26] by P3TERX.COM

 -------------------------
 WARP 客户端状态 : 运行中
 SOCKS5 代理端口 : 未开启
 -------------------------

管理 WARP 官方客户端：

 0. 返回主菜单
 -
 1. 开启 SOCKS5 代理
 2. 关闭 SOCKS5 代理
 3. 重启 WARP 官方客户端
 4. 卸载 WARP 官方客户端

请输入选项: 1

WARP 2021.10.0
Cloudflare
CLI to the WARP service daemon

USAGE:
    warp-cli [FLAGS] [SUBCOMMAND]

FLAGS:
        --accept-tos    Accept the Terms of Service agreement
    -h, --help          Prints help information
    -l                  Listen for status changes and DNS logs (if enabled)
    -V, --version       Prints version information

SUBCOMMANDS:
    register                    Register with the WARP API, replacing any existing registration (Must be run before
                                first connection!)
    teams-enroll                Enroll with Cloudflare for Teams
    delete                      Delete current registration
    rotate-keys                 Generate a new key-pair, keeping the current registration
    status                      Ask the daemon to send the current status
    warp-stats                  Retrieve the stats for the current WARP connection
    settings                    Retrieve the current application settings
    connect                     Connect to WARP (Connection progress can be monitored with -l)
    disconnect                  Disconnect from WARP
    enable-always-on            Enable Always-On mode, meaning WARP is connected whenever possible
    disable-always-on           Disable Always-On mode
    disable-wifi                Automatically disable WARP on Wi-Fi networks
    enable-wifi                 Allow WARP on Wi-Fi networks
    disable-ethernet            Automatically disable WARP on ethernet networks
    enable-ethernet             Allow WARP on ethernet networks
    add-trusted-ssid            Add a trusted Wi-Fi network for which WARP will be automatically disconnected
    remove-trusted-ssid         Remove a trusted Wi-Fi network
    exclude-private-ips         Exclude private IP ranges from tunnel
    enable-dns-log              Enable DNS logging (Use with the -l option)
    disable-dns-log             Disable DNS logging
    account                     Display the account associated with the current registration
    devices                     Display the list of devices associated with the current registration
    network                     Display the current network information
    set-mode                    
    set-families-mode           
    set-license                 Attach the current registration to a different account using a license key
    set-gateway                 Force the app to use the specified Gateway ID for DNS queries
    clear-gateway               Clear the Gateway ID
    set-custom-endpoint         Force the client to connect to the specified IP:PORT endpoint
    clear-custom-endpoint       Remove the custom endpoint setting
    add-excluded-route          Add an excluded IP
    remove-excluded-route       Remove an excluded IP
    get-excluded-routes         Get the list of excluded routes
    get-included-routes         Get the list of included routes
    get-excluded-hosts          Get the list of excluded hosts
    get-included-hosts          Get the list of included hosts
    add-excluded-host           Add an excluded host
    remove-excluded-host        Remove an excluded host
    add-fallback-domain         Add a domain that should be resolved with the fallback resolver instead of WARP's
    remove-fallback-domain      Stop a domain from being resolved with the fallback resolver
    get-fallback-domains        Get the list of domains that go to the fallback resolver
    restore-fallback-domains    Restore the list of fallback resolver domains to its default value
    get-device-posture          Get the current device posture
    override                    Temporarily override MDM policies that require the client to stay enabled
    set-proxy-port              Set the listening port for WARP proxy (127.0.0.1:{port})
    is-mode-switch-allowed      Outputs true if Teams users should be able to change connection mode, or false if
                                not.
    reset-settings              Restore settings to default
    get-organization            Get the name of the Teams organization attached to the current registration.
    get-support-url             Get the support url for the current Teams organization.
    get-pause-end               Retrieve the pause end time
    get-override-end            Retrieve the admin override end time
    help                        Prints this message or the help of the given subcommand(s)
Please accept the WARP Terms of Service by running this command in a TTY or by passing the --accept-tos flag.
[INFO] Setting up WARP Proxy Mode...
NOTICE:

Cloudflare only collects limited DNS query and traffic data (excluding payload)
that is sent to our network when you have the app enabled on your device. We
will not sell, rent, share, or otherwise disclose your personal information to
anyone, except as otherwise described in this Policy, without first providing
you with notice and the opportunity to consent. All information is handled in
accordance with our Privacy Policy.

More information is available at:
- https://www.cloudflare.com/application/terms/
- https://www.cloudflare.com/application/privacypolicy/

Accept Terms of Service and Privacy Policy? [y/N] y

Success
[INFO] Connecting to WARP...
Success
[INFO] Enable WARP Always-On...
Success
[INFO] Status check in progress...

 ----------------------------
 WARP Client	: Running
 SOCKS5 Port	: Off
 ----------------------------

[INFO] Done.

**Comment by Potterli20** [comment]
root@debian:~# curl -I http://127.0.0.1:4000
curl: (7) Failed to connect to 127.0.0.1 port 4000: Connection refused
root@debian:~# warp-cli settings 
Always On: true
Switch Locked: false
Mode: WarpProxy
Proxy listening on: 127.0.0.1:4000
Cloudflare for Families: Off
Disabled for WiFi: false
Disabled for Ethernet: false
Enable DNS logging: false
Fallback domains:
  intranet
  internal
  private
  localdomain
  domain
  lan
  home
  host
  corp
  local
  localhost
  home.arpa
  invalid
  test
Teams Registration by Daemon: false

**Comment by liuyoujiu** [comment]
是CF的WARP更新了，你可以自己手动注册一下`warp-cli register`
或者等P大更新脚本

**Comment by Potterli20** [comment]
> 是CF的WARP更新了，你可以自己手动注册一下`warp-cli register`
> 或者等P大更新脚本

应该是逻辑变了，我用了三个步骤，就好了。脚本真的要更新了

**Comment by sunzjy** [comment]
> > 是CF的WARP更新了，你可以自己手动注册一下`warp-cli register`
> > 或者等P大更新脚本
> 
> 应该是逻辑变了，我用了三个步骤，就好了。脚本真的要更新了

具体用了哪三个步骤后成功开启S5了？可以分享一下吗？

**Comment by asterriya** [comment]
如何激活袜子代理模式，有人能帮我吗？我尝试使用warp-cli，但它没有帮助。

**Comment by joyoner** [comment]
这个问题貌似仍未解决，干净的环境全新安装。

root@SGP-AWS:~# warp-cli register
Success
root@SGP-AWS:~# warp-cli set-mode proxy
Success
root@SGP-AWS:~# warp-cli set-proxy-port 30000
Success
root@SGP-AWS:~# warp-cli settings
Always On: true
Switch Locked: false
Mode: WarpProxy
Proxy listening on: 127.0.0.1:30000
Cloudflare for Families: Off
Disabled for WiFi: false
Disabled for Ethernet: false
Enable DNS logging: false
Excluded routes:
  10.0.0.0/8 (Local network)
  100.64.0.0/10 (Local network)
  169.254.0.0/16 (Local network)
  172.16.0.0/12 (Local network)
  192.0.0.0/24 (Local network)
  192.168.0.0/16 (Local network)
  224.0.0.0/24 (Local network)
  240.0.0.0/4 (Local network)
  255.255.255.255/32 (Local network)
  fe80::/10 (Local network)
  fd00::/8 (Local network)
  ff01::/16 (Local network)
  ff02::/16 (Local network)
  ff03::/16 (Local network)
  ff04::/16 (Local network)
  ff05::/16 (Local network)
Fallback domains:
  intranet
  internal
  private
  localdomain
  domain
  lan
  home
  host
  corp
  local
  localhost
  home.arpa
  invalid
  test
Teams Registration by Daemon: false
root@SGP-AWS:~# warp-cli connect
Success
root@SGP-AWS:~# warp-cli warp-stats
Error: WARP is not connected.
root@SGP-AWS:~#

**Comment by Potterli20** [comment]
> 这个问题貌似仍未解决，干净的环境全新安装。
> 
> root@SGP-AWS:~# warp-cli register Success root@SGP-AWS:~# warp-cli set-mode proxy Success root@SGP-AWS:~# warp-cli set-proxy-port 30000 Success root@SGP-AWS:~# warp-cli settings Always On: true Switch Locked: false Mode: WarpProxy Proxy listening on: 127.0.0.1:30000 Cloudflare for Families: Off Disabled for WiFi: false Disabled for Ethernet: false Enable DNS logging: false Excluded routes: 10.0.0.0/8 (Local network) 100.64.0.0/10 (Local network) 169.254.0.0/16 (Local network) 172.16.0.0/12 (Local network) 192.0.0.0/24 (Local network) 192.168.0.0/16 (Local network) 224.0.0.0/24 (Local network) 240.0.0.0/4 (Local network) 255.255.255.255/32 (Local network) fe80::/10 (Local network) fd00::/8 (Local network) ff01::/16 (Local network) ff02::/16 (Local network) ff03::/16 (Local network) ff04::/16 (Local network) ff05::/16 (Local network) Fallback domains: intranet internal private localdomain domain lan home host corp local localhost home.arpa invalid test Teams Registration by Daemon: false root@SGP-AWS:~# warp-cli connect Success root@SGP-AWS:~# warp-cli warp-stats Error: WARP is not connected. root@SGP-AWS:~#

重新注册，建议用密钥，先用warp注册，然后更换密钥

**Comment by joyoner** [comment]
依旧无法connect，等脚本更新。
