### ISSUE TITLE
This operating system is not supported.

### ISSUE THREAD

**Issue by quanjw** [P3TERX/warp.sh#40]
## this is error
[root@***-VM ~]# uname
Linux
[root@***-VM ~]# bash <(curl -fsSL git.io/warp.sh) install

System Information
---------------------------------------------------
  Operating System: CentOS Linux 7 (Core)
      Linux Kernel: 5.15.5-1.el7.elrepo.x86_64
      Architecture: x86_64
    Virtualization: kvm
---------------------------------------------------

[INFO] Installing Cloudflare WARP Client...
[ERROR] This operating system is not supported.

## this is successful
[root@***-VM ~]# bash <(curl -fsSL git.io/warp.sh) d

I don't know why this happens.

**Comment by P3TERX** [comment]
The official WARP client is not available for CentOS 7
