### ISSUE TITLE
在同目录下运行脚本，貌似没调用已生成的配置文件

### ISSUE THREAD

**Issue by Sakura1338** [P3TERX/warp.sh#44]
用了wgcf生成了warp+的配置文件，但在同目录下运行脚本，看起来并没有顺利调用，连上wireguard网络后使用curl查询也只是单纯显示warp=on
![image](https://user-images.githubusercontent.com/61232882/147388455-436b7876-0232-414f-a6dc-f8b8acdc76b8.png)

![image](https://user-images.githubusercontent.com/61232882/147388439-bd93e466-e43b-46c6-88a6-d245779d1a5d.png)

**Comment by P3TERX** [comment]
要用`wgcf generate`命令生成 WireGuard 配置文件`wgcf-profile.conf`。
`wgcf-account.toml`是账户文件，脚本不对这个文件做识别，如果你没生成`wgcf-profile.conf`会被新的文件覆盖掉，也就等于是新建了个普通 WARP WireGuard 配置文件。

还有就是有时要刷新一下配置文件才会生效。
```
wgcf update
wgcf generate
```
