### ISSUE TITLE
centos隔段时间就要重新跑一次脚本

### ISSUE THREAD

**Issue by vectoriann** [P3TERX/warp.sh#49]
大佬的脚本帮了大忙！我用的是搬瓦工，ss代理在路由器，通过大佬的脚本解锁了Netflix，不过有个问题，隔一段时间后就会失效，具体表现在netflix只能看自制剧，重新跑一次 bash <(curl -fsSL git.io/warp.sh) d  就可以了，我在文档里找不到这个问题或者相关的解释，issues里也没找到，大佬能解答下吗感谢感谢

**Comment by crazypeace** [comment]
就是隔一段时间你的warp的那个出口就被Netflix识别到，放到黑名单了。

**Comment by P3TERX** [comment]
同一个 IP 登录 Netflix 的人多了就会被拉黑，你重新跑一次相当于重启、重连，就重新获取了一个新的出口 IP 。不过目前基本上热门地区的 IP 都被整段被拉黑了。
