### ISSUE TITLE
error openvz Ubuntu 20.04 lts

### ISSUE THREAD

**Issue by RatedR9** [P3TERX/warp.sh#50]
openvz   Ubuntu 20.04 lts

[INFO] Starting WireGuard...
Created symlink /etc/systemd/system/multi-user.target.wants/wg-quick@wgcf.service → /lib/systemd/system/wg-quick@.service.
Job for wg-quick@wgcf.service failed because the control process exited with error code.
See "systemctl status wg-quick@wgcf.service" and "journalctl -xe" for details.
[ERROR] WireGuard failure to run!
-- Logs begin at Mon 2021-11-15 06:17:46 UTC, end at Mon 2022-02-07 12:44:15 UTC. --
Feb 07 12:28:06 Sonmbs systemd[1]: Starting WireGuard via wg-quick(8) for wgcf...
Feb 07 12:28:07 Sonmbs wg-quick[442923]: [#] ip link add wgcf type wireguard
Feb 07 12:28:07 Sonmbs wg-quick[442930]: RTNETLINK answers: Operation not supported
Feb 07 12:28:07 Sonmbs wg-quick[442923]: [!] Missing WireGuard kernel module. Falling back to slow userspace implementation.Feb 07 12:28:07 Sonmbs wg-quick[442923]: [#] wireguard-go wgcf
Feb 07 12:28:07 Sonmbs wg-quick[442931]: ┌──────────────────────────────────────────────────────┐
Feb 07 12:28:07 Sonmbs wg-quick[442931]: │                                                      │
Feb 07 12:28:07 Sonmbs wg-quick[442931]: │   Running wireguard-go is not required because this  │
Feb 07 12:28:07 Sonmbs wg-quick[442931]: │   kernel has first class support for WireGuard. For  │
Feb 07 12:28:07 Sonmbs wg-quick[442931]: │   information on installing the kernel module,       │
Feb 07 12:28:07 Sonmbs wg-quick[442931]: │   please visit:                                      │
Feb 07 12:28:07 Sonmbs wg-quick[442931]: │         https://www.wireguard.com/install/           │
Feb 07 12:28:07 Sonmbs wg-quick[442931]: │                                                      │
Feb 07 12:28:07 Sonmbs wg-quick[442931]: └──────────────────────────────────────────────────────┘
Feb 07 12:28:07 Sonmbs wg-quick[442931]: ERROR: (wgcf) 2022/02/07 12:28:07 Failed to create TUN device: CreateTUN("wgcf") failed; /dev/net/tun does not exist
Feb 07 12:28:07 Sonmbs wg-quick[442936]: Unable to access interface: Protocol not supported
Feb 07 12:28:07 Sonmbs wg-quick[442923]: [#] ip link delete dev wgcf
Feb 07 12:28:07 Sonmbs wg-quick[442937]: Cannot find device "wgcf"
Feb 07 12:28:07 Sonmbs systemd[1]: wg-quick@wgcf.service: Main process exited, code=exited, status=1/FAILURE
Feb 07 12:28:07 Sonmbs systemd[1]: wg-quick@wgcf.service: Failed with result 'exit-code'.
Feb 07 12:28:07 Sonmbs systemd[1]: Failed to start WireGuard via wg-quick(8) for wgcf.
Feb 07 12:31:09 Sonmbs systemd[1]: Starting WireGuard via wg-quick(8) for wgcf...
Feb 07 12:31:09 Sonmbs wg-quick[443791]: [#] ip link add wgcf type wireguard
Feb 07 12:31:09 Sonmbs wg-quick[443798]: RTNETLINK answers: Operation not supported
Feb 07 12:31:09 Sonmbs wg-quick[443791]: [!] Missing WireGuard kernel module. Falling back to slow userspace implementation.Feb 07 12:31:09 Sonmbs wg-quick[443791]: [#] wireguard-go wgcf
Feb 07 12:31:09 Sonmbs wg-quick[443799]: ┌──────────────────────────────────────────────────────┐
Feb 07 12:31:09 Sonmbs wg-quick[443799]: │                                                      │
Feb 07 12:31:09 Sonmbs wg-quick[443799]: │   Running wireguard-go is not required because this  │
Feb 07 12:31:09 Sonmbs wg-quick[443799]: │   kernel has first class support for WireGuard. For  │
Feb 07 12:31:09 Sonmbs wg-quick[443799]: │   information on installing the kernel module,       │
Feb 07 12:31:09 Sonmbs wg-quick[443799]: │   please visit:                                      │
Feb 07 12:31:09 Sonmbs wg-quick[443799]: │         https://www.wireguard.com/install/           │
Feb 07 12:31:09 Sonmbs wg-quick[443799]: │                                                      │
Feb 07 12:31:09 Sonmbs wg-quick[443799]: └──────────────────────────────────────────────────────┘
Feb 07 12:31:09 Sonmbs wg-quick[443799]: ERROR: (wgcf) 2022/02/07 12:31:09 Failed to create TUN device: CreateTUN("wgcf") failed; /dev/net/tun does not exist
Feb 07 12:31:09 Sonmbs wg-quick[443804]: Unable to access interface: Protocol not supported
Feb 07 12:31:09 Sonmbs wg-quick[443791]: [#] ip link delete dev wgcf
Feb 07 12:31:09 Sonmbs wg-quick[443805]: Cannot find device "wgcf"
Feb 07 12:31:09 Sonmbs systemd[1]: wg-quick@wgcf.service: Main process exited, code=exited, status=1/FAILURE
Feb 07 12:31:09 Sonmbs systemd[1]: wg-quick@wgcf.service: Failed with result 'exit-code'.
Feb 07 12:31:09 Sonmbs systemd[1]: Failed to start WireGuard via wg-quick(8) for wgcf.
Feb 07 12:36:53 Sonmbs systemd[1]: Starting WireGuard via wg-quick(8) for wgcf...
Feb 07 12:36:53 Sonmbs wg-quick[444807]: [#] ip link add wgcf type wireguard
Feb 07 12:36:53 Sonmbs wg-quick[444815]: RTNETLINK answers: Operation not supported
Feb 07 12:36:53 Sonmbs wg-quick[444807]: [!] Missing WireGuard kernel module. Falling back to slow userspace implementation.Feb 07 12:36:53 Sonmbs wg-quick[444807]: [#] wireguard-go wgcf
Feb 07 12:36:53 Sonmbs wg-quick[444816]: ┌──────────────────────────────────────────────────────┐
Feb 07 12:36:53 Sonmbs wg-quick[444816]: │                                                      │
Feb 07 12:36:53 Sonmbs wg-quick[444816]: │   Running wireguard-go is not required because this  │
Feb 07 12:36:53 Sonmbs wg-quick[444816]: │   kernel has first class support for WireGuard. For  │
Feb 07 12:36:53 Sonmbs wg-quick[444816]: │   information on installing the kernel module,       │
Feb 07 12:36:53 Sonmbs wg-quick[444816]: │   please visit:                                      │
Feb 07 12:36:53 Sonmbs wg-quick[444816]: │         https://www.wireguard.com/install/           │
Feb 07 12:36:53 Sonmbs wg-quick[444816]: │                                                      │
Feb 07 12:36:53 Sonmbs wg-quick[444816]: └──────────────────────────────────────────────────────┘
Feb 07 12:36:53 Sonmbs wg-quick[444816]: ERROR: (wgcf) 2022/02/07 12:36:53 Failed to create TUN device: CreateTUN("wgcf") failed; /dev/net/tun does not exist
Feb 07 12:36:53 Sonmbs wg-quick[444821]: Unable to access interface: Protocol not supported
Feb 07 12:36:53 Sonmbs wg-quick[444807]: [#] ip link delete dev wgcf
Feb 07 12:36:53 Sonmbs wg-quick[444822]: Cannot find device "wgcf"
Feb 07 12:36:53 Sonmbs systemd[1]: wg-quick@wgcf.service: Main process exited, code=exited, status=1/FAILURE
Feb 07 12:36:53 Sonmbs systemd[1]: wg-quick@wgcf.service: Failed with result 'exit-code'.
Feb 07 12:36:53 Sonmbs systemd[1]: Failed to start WireGuard via wg-quick(8) for wgcf.
Feb 07 12:44:15 Sonmbs systemd[1]: Starting WireGuard via wg-quick(8) for wgcf...
Feb 07 12:44:15 Sonmbs wg-quick[448050]: [#] ip link add wgcf type wireguard
Feb 07 12:44:15 Sonmbs wg-quick[448057]: RTNETLINK answers: Operation not supported
Feb 07 12:44:15 Sonmbs wg-quick[448050]: [!] Missing WireGuard kernel module. Falling back to slow userspace implementation.Feb 07 12:44:15 Sonmbs wg-quick[448050]: [#] wireguard-go wgcf
Feb 07 12:44:15 Sonmbs wg-quick[448058]: ┌──────────────────────────────────────────────────────┐
Feb 07 12:44:15 Sonmbs wg-quick[448058]: │                                                      │
Feb 07 12:44:15 Sonmbs wg-quick[448058]: │   Running wireguard-go is not required because this  │
Feb 07 12:44:15 Sonmbs wg-quick[448058]: │   kernel has first class support for WireGuard. For  │
Feb 07 12:44:15 Sonmbs wg-quick[448058]: │   information on installing the kernel module,       │
Feb 07 12:44:15 Sonmbs wg-quick[448058]: │   please visit:                                      │
Feb 07 12:44:15 Sonmbs wg-quick[448058]: │         https://www.wireguard.com/install/           │
Feb 07 12:44:15 Sonmbs wg-quick[448058]: │                                                      │
Feb 07 12:44:15 Sonmbs wg-quick[448058]: └──────────────────────────────────────────────────────┘
Feb 07 12:44:15 Sonmbs wg-quick[448058]: ERROR: (wgcf) 2022/02/07 12:44:15 Failed to create TUN device: CreateTUN("wgcf") failed; /dev/net/tun does not exist
Feb 07 12:44:15 Sonmbs wg-quick[448063]: Unable to access interface: Protocol not supported
Feb 07 12:44:15 Sonmbs wg-quick[448050]: [#] ip link delete dev wgcf
Feb 07 12:44:15 Sonmbs wg-quick[448064]: Cannot find device "wgcf"
Feb 07 12:44:15 Sonmbs systemd[1]: wg-quick@wgcf.service: Main process exited, code=exited, status=1/FAILURE
Feb 07 12:44:15 Sonmbs systemd[1]: wg-quick@wgcf.service: Failed with result 'exit-code'.
Feb 07 12:44:15 Sonmbs systemd[1]: Failed to start WireGuard via wg-quick(8) for wgcf.

**Comment by P3TERX** [comment]
OVZ 的鸡要去管理面板开 TAP/TUN 功能才能用
