### ISSUE TITLE
提问:  关于ip rule

### ISSUE THREAD

**Issue by mlyxshi** [P3TERX/warp.sh#51]
>默认的配置文件没有外部对 VPS 本机 IP 网络访问的相关路由规则，一旦直接使用 VPS 就会直接失联
PostUp = ip -4 rule add from <替换IPv4地址> lookup main
PostDown = ip -4 rule delete from <替换IPv4地址> lookup main

加了`PostUp = ip -4 rule add from <替换IPv4地址> lookup main`外部可以访问 VPS 本机

看完[https://ro-che.info/articles/2021-02-27-linux-routing](https://ro-che.info/articles/2021-02-27-linux-routing)这篇文章后，大致明白了wg-quick的路由设置。

```
root@ubuntu:~# ip rule 
0:	from all lookup local
18:	from 10.0.0.44 lookup main
32764:	from all lookup main suppress_prefixlength 0
32765:	not from all fwmark 0xca6c lookup 51820
32766:	from all lookup main
32767:	from all lookup default
```
```
root@ubuntu:~# ip route
default via 10.0.0.1 dev enp0s3 proto static 
10.0.0.0/24 dev enp0s3 proto kernel scope link src 10.0.0.44 
```

wireshark 抓包，在服务器里curl ip.sb实际走wireguard 网卡
![https://cdn.mlyxshi.com/5.png](https://cdn.mlyxshi.com/5.png)

我的理解是, `Local Process` curl  请求， Routing 阶段因为source ip是10.0.0.44(VPC IP)，所以匹配 `PostUp = ip -4 rule add from <替换IPv4地址> lookup main`,main table 默认走enp0s3，不会走wireguard的网卡。

按照你的blog配置，网络就是预期的应有行为，没有问题。
我的理解是`PostUp = ip -4 rule add from <替换IPv4地址> lookup main`后，所有本机产生的流量(source ip是10.0.0.44)都匹配到main table, 不会匹配到`32765:	not from all fwmark 0xca6c lookup 51820`。与抓包事实不符， 请问我哪里理解错了呢？

**Comment by mlyxshi** [comment]
[关于Source Address Selection](https://unix.stackexchange.com/a/282575)

**Comment by liudongmiao** [comment]
我个人的规则：
1. 部分网段默认走 wgcf
2.  如果这些网段来访问我的服务，保证他们可以访问得到


```
# 以下这两个是配置在 wgcf.conf 中的 AllowedIPs
# 这样，确保 172.16.0.2（本机虚拟）以及 142.250.0.0/15（某网段）默认走 wgcf
$ ip route show  | grep wgcf
142.250.0.0/15 dev wgcf scope link 
172.16.0.2 dev wgcf scope link 
```

```
# 添加一个 table eth0，数字，名称随意，不冲突即可
# 这个可以永久
$ echo 117 eth0 > /etc/iproute2/rt_tables
```

```
# 给 table eth0 配置路由规则：走本机默认网关
# 这个也可以永久
$ ip route show table eth0
default via xxx.xxx.xxx.1 dev xxx # 使用实际值
```

```
# 本机 eth0 出去的，走 eth0
# 这个也可以永久
$ ip rule show | grep eth0
from xxx.xxx.xxx.xxx lookup eth0 
```

当然也可以加个更复杂的规则，让虚拟ip出去的走 wgcf，然后弄个 wgcf 的 table。
