### ISSUE TITLE
该脚本如何填写 license_key

### ISSUE THREAD

**Issue by OPPO9008** [P3TERX/warp.sh#53]
我朋友送了我一个 warp + 的license，想试试对vps有没有优化，但是发现没有warp-cli程序，不知道什么地方输入license

**Comment by P3TERX** [comment]
1. WARP+ 实际上对网速没有提升作用，从官方以往提供的资料来看只是对使用了 Cloudflare CDN 的网站有作用，但实测感知不到差异。所以官方没有刻意去宣传 WARP+ 的区别，并似乎有意在模糊化处理 WARP 和 WARP+ 的概念。
2. 正因为以上原因，这个脚本暂时就没有直接提供导入 license key 的功能。不过我还是说一下目前要用我这个脚本该怎么用 WARP+ ：
    - WARP WireGuard 网络：通过 [wgcf](https://github.com/ViRb3/wgcf) 使用 license 生成 WARP+ 的 WireGuard 配置文件，然后再通过此脚本调用。 
    - WARP 官方客户端：首先装客户端，然后通过`warp-cli set-license`命令导入 license 。
