### ISSUE TITLE
 WARP 官方客户端无法启动

### ISSUE THREAD

**Issue by icrazt** [P3TERX/warp.sh#54]
上周使用了 `自动配置 WARP WireGuard 双栈全局网络` ，很顺利的开启了WARP。但今天突然发现 WARP 连接断开，关闭 WARP WireGuard 网络后网络访问才正常。
![SecureCRT_0jif3RC4dZ](https://user-images.githubusercontent.com/29837321/156601744-bb0edf90-f78b-4478-9a90-3d464e278c6c.png)

使用脚本重新配置，重启系统均没有解决问题，最后使用 menu 时发现似乎是  WARP 官方客户端无法启动导致的：
``` shell
Cloudflare WARP 一键安装脚本 [beta32] by P3TERX.COM

 -------------------------
 WARP 客户端状态 : 未运行
 SOCKS5 代理端口 : 未开启
 -------------------------

管理 WARP 官方客户端：

 0. 返回主菜单
 -
 1. 开启 SOCKS5 代理
 2. 关闭 SOCKS5 代理
 3. 重启 WARP 官方客户端
 4. 卸载 WARP 官方客户端

请输入选项: 3

[INFO] Restarting Cloudflare WARP Client...
Failed to restart warp-svc.service: Unit warp-svc.service not found.
[ERROR] Cloudflare WARP Client failure to run!
-- Logs begin at Fri 2022-02-25 21:40:43 GMT, end at Thu 2022-03-03 15:49:36 GMT. --
-- No entries --
```
------------------------------
**其他信息**
使用了 `git.io/warp.sh` 获取的最新脚本。
系统：
![SecureCRT_xT3no1PA4c](https://user-images.githubusercontent.com/29837321/156602322-03493db1-9837-4657-8cc2-281ca4de38c8.png)

**Comment by icrazt** [comment]
早上试了一下，虽然客户端的报错还是上面那样，但 WARP 可以正常启用，应该是受官方的影响：https://github.com/ViRb3/wgcf/issues/158#issuecomment-1058508174

**Comment by icrazt** [comment]
早上试了一下，虽然客户端的报错还是上面那样，但 WARP 可以正常启用，应该是受官方的影响：https://github.com/ViRb3/wgcf/issues/158#issuecomment-1058508174

**Comment by P3TERX** [comment]
1. WARP 官方客户端和 WARP WireGuard 网络是 WARP 的两种使用方式，二者功能是独立的。WireGuard 方式并不依赖官方客户端，没装官方客户端去使用相关功能肯定是有错误提示的。
2. 昨天 Cloudflare 官方对 WireGuard 方式使用 WARP 采取了试探性的限制，可能跟最近部分用户的滥用行为有关。

**Comment by icrazt** [comment]
了解了，谢谢解答~
