### ISSUE TITLE
配置后无法联网

### ISSUE THREAD

**Issue by FLIER001** [P3TERX/warp.sh#55]
使用脚本配置后 centos 8 无法联网，IPV4和IPV6均是unconnected状态。

使用了好几个月一直正常，今天发现VPS无法联网，才搞清楚是这里出了问题。

**Comment by SxLvIo** [comment]
cloudflare那边封了🙂昨天我也用不到

**Comment by P3TERX** [comment]
https://github.com/ViRb3/wgcf/issues/158#issuecomment-1058508174
昨天 Cloudflare 官方对 WireGuard 方式使用 WARP 采取了试探性的限制，可能跟最近部分用户的滥用行为有关。
