### ISSUE TITLE
CentOS 7 无法安装，提示系统不支持

### ISSUE THREAD

**Issue by voiaya** [P3TERX/warp.sh#60]
System Information
---------------------------------------------------
  Operating System: CentOS Linux 7 (Core)
      Linux Kernel: 3.10.0-1160.31.1.el7.x86_64
      Architecture: x86_64
    Virtualization: microsoft
---------------------------------------------------

[INFO] Installing Cloudflare WARP Client...
[ERROR] This operating system is not supported.

**Comment by P3TERX** [comment]
Cloudflare 官方做不支持，而且现在 CentOS 已经被扫进历史垃圾堆了。
