### ISSUE TITLE
WARP 官方客户端 SOCKS5 代理 自动停止

### ISSUE THREAD

**Issue by v2-free** [P3TERX/warp.sh#64]
Debian 10 操作系统，
bash <(curl -fsSL git.io/warp.sh) s5
配置官方客户端SOCKS5 代理，
运行一段时间后 自动停止。

这时 netstat 命令查看 127.0.0.1:40000 依然在监听，但是
bash <(curl -fsSL git.io/warp.sh) menu
显示：
WARP 客户端状态 : 运行中
SOCKS5 代理端口 : 未开启

希望大佬的脚本能自动处理这种情况，一旦自动停止就给它自动重启一下，保持代理不掉线。

**Comment by erbanku** [comment]
同，也遇到此问题。

```
 WARP 客户端状态 : 运行中

 SOCKS5 代理端口 : 未开启

 WireGuard 状态 : 运行中
 IPv4 网络状态  : WARP
 IPv6 网络状态  : WARP
```

**Comment by shwangdev** [comment]
一样的问题
