### ISSUE TITLE
 /bin/warp-svc: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.29' not found (required by /bin/warp-svc)

### ISSUE THREAD

**Issue by jiangxiaoqiang** [P3TERX/warp.sh#68]
手工安装了glibc，可以指定glibc的本地路径么？

**Comment by P3TERX** [comment]
搜了下发现这个应该是你发的吧？
https://stackoverflow.com/questions/73188397/bin-warp-svc-lib-x86-64-linux-gnu-libc-so-6-version-glibc-2-29-not-found
之前 Cloudflare 只提供了 Ubuntu 20.04 的包，脚本就没做 Ubuntu 的版本判断，所有版本就直接怼上去了，所以说 18.04 会有兼容问题 。

**Comment by P3TERX** [comment]
目前已经对 Ubuntu 加了版本判断，能不能用就看官方的了。
