### ISSUE TITLE
IPv6连接失败

### ISSUE THREAD

**Issue by levie-vans** [P3TERX/warp.sh#69]
System Information
---------------------------------------------------
  Operating System: Ubuntu 20.04.4 LTS
      Linux Kernel: 5.4.0-109-generic
      Architecture: x86_64
    Virtualization: kvm
---------------------------------------------------

[INFO] WireGuard is installed and running.
[INFO] Disabling WireGuard...
Removed /etc/systemd/system/multi-user.target.wants/wg-quick@wgcf.service.
[INFO] WireGuard has been disabled.
[INFO] Getting the network interface IPv4 address...
[INFO] IPv4 Address: 192.168.0.2
[INFO] Getting the best MTU value for WireGuard...
[INFO] WireGuard MTU: 1420
[INFO] WireGuard profile (/etc/wireguard/wgcf.conf) generation in progress...
 
----------------------------
 WireGuard       : Running
 IPv4 Network   : Normal
 IPv6 Network   : Unconnected
 ----------------------------

安装过程全程正常，但是IPv6并没有连接成功。

**Comment by P3TERX** [comment]
可能只是 WARP 网络的问题吧。
有时候网络不稳定，脚本也会显示未连接，但实际是已连接的。
