### ISSUE TITLE
git.io无法使用

### ISSUE THREAD

**Issue by zsbai** [P3TERX/warp.sh#71]
现在git.io国内+国外访问全部超时，网上看到GitHub在4月29日已经停止git.io的服务了

**Comment by P3TERX** [comment]
可以用啊，只是不能再添加新的链接了。微软砍刀部又立功了。
如果是解析错误可以用原始地址：
https://raw.githubusercontent.com/P3TERX/warp.sh/main/warp.sh

**Comment by molezz** [comment]
> 可以用啊，只是不能再添加新的链接了。微软砍刀部又立功了。 如果是解析错误可以用原始地址： https://raw.githubusercontent.com/P3TERX/warp.sh/main/warp.sh

IPV6的机器需要用这个原始地址，gitio无法解析到了
