### ISSUE TITLE
warp双栈在AWS Ubuntu 20下隔一段时间就断网，非要重启以下

### ISSUE THREAD

**Issue by ckaak** [P3TERX/warp.sh#81]
在Ubuntu 20.04.5 LTS (GNU/Linux 5.15.0-1021-aws x86_64) 上配置WARP WireGuard 双栈全局网络，隔一段时间就断网，重启以后恢复，然后隔一段时间又断网，又要重启。单IPV4没问题。

但是在DO Debian11  4.19.0-22-cloud-amd64 WARP WireGuard 双栈全局网络就完全没问题。

**Comment by cjrzh** [comment]
同样

**Comment by P3TERX** [comment]
我博客上的留言有几个 Ubuntu 出类似的问题，感觉是 Ubuntu 的锅。
我的 VPS 全员 Debian ，有些放了一年多没管，上面的 WARP 还好好的。
Server 版系统还是推荐 Debian 。
总之 重启、重装、重买，解决一切问题。

**Comment by Extreme-Icer** [comment]
> 我博客上的留言有几个 Ubuntu 出类似的问题，感觉是 Ubuntu 的锅。 我的 VPS 全员 Debian ，有些放了一年多没管，上面的 WARP 还好好的。 Server 版系统还是推荐 Debian 。 总之 重启、重装、重买，解决一切问题。

我自己的vps debian12 linux6.1 wireguard弄warp+ hk 直接丢包40% 不知道为什么 也是双栈全局 也是会断个十几秒
