### ISSUE TITLE
无法安装，CnetOS7提示不支持此操作系统。

### ISSUE THREAD

**Issue by iLoveElysia** [P3TERX/warp.sh#84]
System Information
---------------------------------------------------
  Operating System: CentOS Linux 7 (Core)
      Linux Kernel: 3.10.0-1160.83.1.el7.x86_64
      Architecture: x86_64
    Virtualization: kvm
---------------------------------------------------

[INFO] Installing Cloudflare WARP Client...
[ERROR] This operating system is not supported.
You have new mail in /var/spool/mail/root

**Comment by FutureApple** [comment]
貌似是因为内核版本过低导致的

**Comment by FutureApple** [comment]
还是不行

**Comment by FutureApple** [comment]
https://pkg.cloudflareclient.com/dists/7/main/binary-x86_64/repodata/repomd.xml   这个地址404了

**Comment by feeloho** [comment]
`System Information
---------------------------------------------------
  Operating System: CentOS Linux 7 (Core)
      Linux Kernel: 5.3.8-1.el7.elrepo.x86_64
      Architecture: x86_64
    Virtualization: kvm
---------------------------------------------------

[INFO] Installing Cloudflare WARP Client...
[ERROR] This operating system is not supported.`

**Comment by feeloho** [comment]
```
System Information
---------------------------------------------------
  Operating System: CentOS Linux 7 (Core)
      Linux Kernel: 5.3.8-1.el7.elrepo.x86_64
      Architecture: x86_64
    Virtualization: kvm
---------------------------------------------------

[INFO] Installing Cloudflare WARP Client...
[ERROR] This operating system is not supported.
```

**Comment by feeloho** [comment]
我也出现了
```
System Information
---------------------------------------------------
  Operating System: CentOS Linux 7 (Core)
      Linux Kernel: 5.3.8-1.el7.elrepo.x86_64
      Architecture: x86_64
    Virtualization: kvm
---------------------------------------------------

[INFO] Installing Cloudflare WARP Client...
[ERROR] This operating system is not supported.
```

**Comment by P3TERX** [comment]
官方没给 CentOS 7 的包，当然不支持。￣□￣｜｜
官方客户端支持的系统和包在这里可以看到：https://pkg.cloudflareclient.com/packages/cloudflare-warp
