### ISSUE TITLE
使用脚本配置ipv4/6均失败

### ISSUE THREAD

**Issue by qaxc** [P3TERX/warp.sh#85]
[INFO] 正在检查状态...

Cloudflare WARP 一键安装脚本 [beta39] by P3TERX.COM

 -------------------------
 WARP 客户端状态 : 未运行
 SOCKS5 代理端口 : 未开启
 -------------------------
 WireGuard 状态 : 未运行
 IPv4 网络状态  : 正常
 IPv6 网络状态  : 未连接
 -------------------------

 1. 安装 Cloudflare WARP 官方客户端
 2. 自动配置 WARP 客户端 SOCKS5 代理
 3. 管理 Cloudflare WARP 官方客户端
 -
 4. 安装 WireGuard 相关组件
 5. 自动配置 WARP WireGuard IPv4 网络
 6. 自动配置 WARP WireGuard IPv6 网络
 7. 自动配置 WARP WireGuard 双栈全局网络
 8. 管理 WARP WireGuard 网络

请输入选项: 5

System Information
---------------------------------------------------
  Operating System: Ubuntu 18.04.6 LTS
      Linux Kernel: 4.11.8-041108-lowlatency
      Architecture: x86_64
    Virtualization: kvm
---------------------------------------------------

[INFO] Installing wireguard-tools...
Hit:1 http://ap-osaka-1-ad-1.clouds.archive.ubuntu.com/ubuntu bionic InRelease
Get:2 http://ap-osaka-1-ad-1.clouds.archive.ubuntu.com/ubuntu bionic-updates InR                        elease [88.7 kB]
Get:3 http://security.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]
Get:4 http://ap-osaka-1-ad-1.clouds.archive.ubuntu.com/ubuntu bionic-backports I                        nRelease [83.3 kB]
Fetched 261 kB in 2s (148 kB/s)
Reading package lists... Done
Building dependency tree
Reading state information... Done
7 packages can be upgraded. Run 'apt list --upgradable' to see them.
Reading package lists... Done
Building dependency tree
Reading state information... Done
openresolv is already the newest version (3.8.0-1).
iproute2 is already the newest version (4.15.0-2ubuntu1.3).
The following packages were automatically installed and are no longer required:
  amd64-microcode intel-microcode iucode-tool libdbus-glib-1-2
  linux-oracle-5.4-headers-5.4.0-1083 thermald
Use 'apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 7 not upgraded.
Reading package lists... Done
Building dependency tree
Reading state information... Done
wireguard-tools is already the newest version (1.0.20200513-1~18.04.2).
The following packages were automatically installed and are no longer required:
  amd64-microcode intel-microcode iucode-tool libdbus-glib-1-2
  linux-oracle-5.4-headers-5.4.0-1083 thermald
Use 'apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 7 not upgraded.
[INFO] Get CPU architecture ...
[INFO] Architecture: amd64 (dpkg)
[INFO] Get wireguard-go download URL ...
[INFO] Download URL: https://github.com/P3TERX/wireguard-go-builder/releases/dow                        nload/0.0.20230223/wireguard-go-linux-amd64.tar.gz
[INFO] Installing wireguard-go ...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 2143k  100 2143k    0     0  3084k      0 --:--:-- --:--:-- --:--:-- 8679k
[INFO] Done.
[INFO] Disabling WireGuard...
Removed /etc/systemd/system/multi-user.target.wants/wg-quick@wgcf.service.
[INFO] WireGuard has been disabled.
[INFO] Getting the network interface IPv4 address...
[INFO] IPv4 Address: 10.0.0.47
[INFO] Getting the best MTU value for WireGuard...
[INFO] WireGuard MTU: 1420
[INFO] WireGuard profile (/etc/wireguard/wgcf.conf) generation in progress...
================================================================================
# Generated by P3TERX/warp.sh
# Visit https://github.com/P3TERX/warp.sh for more information

[Interface]
PrivateKey = 4LmTJ2KvRRZ+3sgtI4d7XCiaa6p6orx0bDAeRRiG21o=
Address = 172.16.0.2/32,2606:4700:110:82dd:71c1:eab9:777b:f733/128
DNS = 8.8.8.8,8.8.4.4,2001:4860:4860::8888,2001:4860:4860::8844
MTU = 1420
PostUp = ip -4 rule add from 10.0.0.47 lookup main prio 18
PostDown = ip -4 rule delete from 10.0.0.47 lookup main prio 18

[Peer]
PublicKey = bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo=
AllowedIPs = 0.0.0.0/0
Endpoint = 162.159.192.1:2408
================================================================================
sysctl: reading key "net.ipv6.conf.all.stable_secret"
sysctl: reading key "net.ipv6.conf.default.stable_secret"
sysctl: reading key "net.ipv6.conf.ens3.stable_secret"
sysctl: reading key "net.ipv6.conf.lo.stable_secret"
[INFO] Starting WireGuard...
Created symlink /etc/systemd/system/multi-user.target.wants/wg-quick@wgcf.servic                        e → /lib/systemd/system/wg-quick@.service.
一直停在最后这里不动，求解决

**Comment by NoahBishop** [comment]
+1

**Comment by NoahBishop** [comment]
妈的，试了一下午，最后更新系统解决的，内核版本4.几太低了，用这个方法https://askubuntu.com/questions/1388115/how-do-i-update-my-kernel-to-the-latest-one，更新到最新版本6.几解决问题。（wireguard的问题，卡在哪里是因为运行到systemctl enable --now会先enable，然后start，卡在start了，隔壁fscarmen的warp脚本也是类似问题，一样启动不了）

**Comment by 4ft35t** [comment]
Ubuntu 20.04 使用 4.15.0-32  内容，同样会卡在 
```bash
[INFO] Starting WireGuard...
Created symlink /etc/systemd/system/multi-user.target.wants/[wg-quick@wgcf.servic](mailto:wg-quick@wgcf.servic) e → /lib/systemd/system/[wg-quick@.service](mailto:wg-quick@.service).
```

升级内核到 `5.15.0-69` 后，可正常使用。

内核升级方法
```
sudo apt update && sudo apt install linux-headers-5.15.0-69-generic linux-image-5.15.0-69-generic -y && reboot
```
自动重启后，内核升级完成。
