### ISSUE TITLE
 安装报错：“Cloudflare WARP network anomaly, WireGuard tunnel established failed.”

### ISSUE THREAD

**Issue by Mrfuture1** [P3TERX/warp.sh#91]
是在亚马逊云上安装的，报了标题错误。我看打印的日志，获取的ipv4是私有IP，不是公有IP，是因为这个原因吗？怎么修改呢？

**Comment by liyang-lomo** [comment]
我是使用 自动配置 WARP WireGuard IPv6 网络 解决的，openai 能用了，除了star还是star

**Comment by Mrfuture1** [comment]
脚本自动配置完ipv6，还需要再配置啥不

**Comment by P3TERX** [comment]
之前有人搞事情，搞得有些地区原版 WireGuard 没办法用了，具体看[这里](https://p3terx.com/archives/cloudflare-warp-script-issue-and-solution.html)。装官方客户端可解。

**Comment by narutojxl** [comment]
谢谢作者，我的服务器系统是CenOS7，目前还装不了【WARP 官方 Linux 客户端 SOCKS5 代理模式】， 后面有时间重装系统后再试下。
