### ISSUE TITLE
WireGuard网络路由原理

### ISSUE THREAD

**Issue by longzhiri** [P3TERX/warp.sh#92]
你好！请问加上这个路由规则配置就能不影响外部对本机 IP 访问的原理是什么，按道理这条规则会导致所有由本机发起的流量都去main表路由了，而不是WireGuard新建的路由表 
```
PostUp = ip -4 rule add from <替换IPv4地址> lookup main 
```

**Comment by P3TERX** [comment]
原理去问 ChatGPT 吧，它讲的估计比任何人都详细。
